FOOD-48: [Admin] Crear Sucursales
electricpants01/nexventa pull request #47
Opened 2024-06-07 16:18 UTC by Pericena

FOOD-48: https://locotoinnovations.atlassian.net/browse/FOOD-48
Se creo componentes sucursal como también se mejoro NEXSidebar.astro , se elimino datos duplicado de listar usuario admin. 

## Listar sucursal
![image](https://github.com/electricpants01/nexventa/assets/24308878/a90adcca-eefd-4b75-95bc-69489e8fe54a)

## Crear sucursal
![image](https://github.com/electricpants01/nexventa/assets/24308878/6e7f4acb-7fe9-4eaa-a205-d1b0712d0c10)

2024-06-07 17:20 UTC, electricpants01 commented
Podemos borrar añadir imagen, y si acepta las condiciones, ya que no habran diferentes imagenes para distintas sucursales
![image](https://github.com/electricpants01/nexventa/assets/20894460/79ac69aa-ca3a-4e59-8555-e8d3f78fe2ff)

2024-06-07 17:22 UTC, electricpants01 commented
La barra laterial igual, solo deberia estar seleccionado "en naraja" si se esta viendo el modulo "usuario" o "sucursal" 
![image](https://github.com/electricpants01/nexventa/assets/20894460/565ce63c-a57a-47c0-b696-ccbb154d8aee)

2024-06-07 17:23 UTC, electricpants01 requested changes
Me agrada que estemos aprovechando el espacio en los forms y se este dando soporte para mobile, algunos comentarios son necesarios ante de mergear

2024-06-10 14:14 UTC, electricpants01 approved these changes

2024-06-10 16:26 UTC, electricpants01 commented on src/components/admin/sidebar/NEXSidebar.astro
> +                href="/admin/branch/create"p
hay una `p` al final ? habra que eliminarla ?

2024-06-10 16:38 UTC, Pericena commented on src/components/admin/sidebar/NEXSidebar.astro
> +                href="/admin/branch/create"p
Ya esta eliminado estaba por demás la 

`p`

 ing

2024-06-11 21:17 UTC, merged